/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ValidityChecker;

import org.junit.Test;
import static org.junit.Assert.*;

public class ValidityCheckerTest {
    @Test
    public void testSomeMethod() {
        assertTrue(true);
    }
}
